import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync } from 'node:fs';
import path from 'node:path';

/**
 * Tauri v2 ACL 回归测试（B-7 复核遗留缺陷）：
 *
 * 应用自定义命令（lib.rs `generate_handler!` 里的条目）必须逐个以
 * `allow-<command>` 权限写进 capabilities，否则 invoke 会被 ACL 以
 * "not allowed. Command not found" 拒绝。c9ababb 新增
 * acquire/release_library_lock 时漏掉了 capabilities 更新，导致
 * saveLibraryBooks 每次调用都抛错、导入流程的加载遮罩永远关不上。
 *
 * 命名约定（以 gen/schemas/acl-manifests.json 的 __app-acl__ 为准）：
 * snake_case 命令名转 kebab-case 权限标识 —— `get_environment_variable`
 * 对应 `allow-get-environment-variable`。capability 文件里的权限条目
 * 既可能是字符串，也可能是带 identifier 的对象（作用域限定的 fs:* 等）。
 *
 * 权限标识本身不是自动生成的：每个命令需要 `src-tauri/permissions/
 * autogenerated/<command>.toml` 显式定义 allow-/deny- 权限（缺失时
 * tauri-build 直接 panic："Permission allow-* not found"），然后再把
 * `allow-<command>` 写进 capabilities。两类缺口这里都拦。
 *
 * 本测试以 lib.rs 的命令清单为准，要求每个枚举了应用命令权限的
 * capabilities 文件都覆盖全部命令，防止以后新增命令再漏注册。
 */

const APP_DIR = path.resolve(__dirname, '../../..');

function extractAppCommands(libRs: string): string[] {
  const start = libRs.indexOf('generate_handler![');
  expect(start, 'lib.rs must contain generate_handler![').toBeGreaterThan(-1);
  const end = libRs.indexOf(']', start);
  const block = libRs.slice(start + 'generate_handler!['.length, end);
  const commands: string[] = [];
  for (const rawLine of block.split('\n')) {
    const line = rawLine.trim().replace(/,$/, '');
    if (!line || line.startsWith('#[') || line.startsWith('//')) continue;
    // 条目形如 `read_dir` / `library_lock::acquire_library_lock`，
    // 命令名 = 最后一段路径的 snake_case 函数名。
    const name = line.split('::').pop()!;
    if (name) commands.push(name);
  }
  return commands;
}

const snakeToKebab = (command: string) => command.replace(/_/g, '-');

function permissionIdentifiers(permissions: unknown[]): string[] {
  return permissions.map((entry) => {
    if (typeof entry === 'string') return entry;
    const identifier = (entry as { identifier?: unknown }).identifier;
    return typeof identifier === 'string' ? identifier : '';
  });
}

describe('tauri app command capability coverage', () => {
  const libRs = readFileSync(path.join(APP_DIR, 'src-tauri/src/lib.rs'), 'utf8');
  const commands = extractAppCommands(libRs);

  it('lib.rs 应当解析出应用命令清单', () => {
    expect(commands).toContain('acquire_library_lock');
    expect(commands).toContain('release_library_lock');
    expect(commands).toContain('parse_epub_metadata');
  });

  it('每个命令都有 permissions/autogenerated/<command>.toml 权限定义', () => {
    const autogeneratedDir = path.join(APP_DIR, 'src-tauri/permissions/autogenerated');
    const withoutDefinition = commands.filter(
      (cmd) => !readdirSync(autogeneratedDir).includes(`${cmd}.toml`),
    );
    expect(
      withoutDefinition,
      `缺少权限定义 toml（tauri-build 会 panic）: ${withoutDefinition.join(', ')}`,
    ).toEqual([]);
  });

  const capabilitiesDir = path.join(APP_DIR, 'src-tauri/capabilities');
  const capabilityFiles = readdirSync(capabilitiesDir).filter((f) => f.endsWith('.json'));

  for (const file of capabilityFiles) {
    it(`${file} 覆盖 lib.rs 全部应用命令的 allow-* 权限`, () => {
      const capability = JSON.parse(readFileSync(path.join(capabilitiesDir, file), 'utf8'));
      const identifiers = permissionIdentifiers(capability.permissions ?? []);
      // 只约束"枚举了应用命令权限"的 capability（即含任一 allow-* 条目），
      // 避免误伤纯插件权限的文件（如 desktop.json 的 cli:default）。
      if (!identifiers.some((p) => p.startsWith('allow-'))) return;

      const missing = commands.filter((cmd) => !identifiers.includes(`allow-${snakeToKebab(cmd)}`));
      expect(
        missing,
        `${file} 缺少 allow-* 权限（invoke 会被 ACL 拒绝）: ${missing.join(', ')}`,
      ).toEqual([]);
    });
  }
});
